import type { Episode, Guest, Topic, Timestamp, Quote, Resource } from '@/types/database'

export const mockTopics: Topic[] = [
  { id: '1', name: 'العلاقات', slug: 'relationships', created_at: '2024-01-01' },
  { id: '2', name: 'تطوير الذات', slug: 'self-growth', created_at: '2024-01-01' },
  { id: '3', name: 'المعنى والهدف', slug: 'meaning', created_at: '2024-01-01' },
  { id: '4', name: 'الصحة النفسية', slug: 'mental-health', created_at: '2024-01-01' },
  { id: '5', name: 'العمل والمهنة', slug: 'career', created_at: '2024-01-01' },
]

export const mockGuests: Guest[] = [
  {
    id: '1',
    name: 'د. سارة الأحمد',
    slug: 'sarah-ahmed',
    bio: 'طبيبة نفسية ومتخصصة في العلاقات الأسرية، لها أكثر من 15 عاماً من الخبرة في مساعدة الأفراد والعائلات.',
    photo_url: null,
    external_links: { twitter: 'https://twitter.com/sarah', linkedin: 'https://linkedin.com/in/sarah' },
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'أحمد العلي',
    slug: 'ahmed-ali',
    bio: 'رائد أعمال ومؤسس عدة شركات ناشئة ناجحة، شغوف بمشاركة تجاربه في ريادة الأعمال.',
    photo_url: null,
    external_links: { twitter: 'https://twitter.com/ahmed', website: 'https://ahmed.com' },
    created_at: '2024-01-01',
  },
  {
    id: '3',
    name: 'نورة القحطاني',
    slug: 'noura-qahtani',
    bio: 'كاتبة ومدربة في مجال تطوير الذات، ألفت عدة كتب حول النمو الشخصي والوعي الذاتي.',
    photo_url: null,
    external_links: { instagram: 'https://instagram.com/noura' },
    created_at: '2024-01-01',
  },
  {
    id: '4',
    name: 'م. خالد الشمري',
    slug: 'khaled-shammari',
    bio: 'مهندس برمجيات ومدير تقني، يشارك خبراته في بناء الفرق التقنية والقيادة.',
    photo_url: null,
    external_links: { linkedin: 'https://linkedin.com/in/khaled' },
    created_at: '2024-01-01',
  },
]

export const mockEpisodes: (Episode & { guest?: Guest | null, topics?: { topic: Topic }[] })[] = [
  {
    id: '1',
    title: 'كيف نبني علاقات صحية ومستدامة؟',
    slug: 'healthy-relationships',
    summary: 'في هذه الحلقة نتحدث مع د. سارة الأحمد عن أسس العلاقات الصحية وكيف نتعامل مع التحديات التي تواجهنا في علاقاتنا اليومية. نناقش أهمية التواصل الفعال والحدود الصحية.',
    key_takeaways: [
      'التواصل الفعال هو أساس كل علاقة ناجحة',
      'وضع الحدود الصحية ليس أنانية بل ضرورة',
      'الاستماع الفعال أهم من الرد السريع',
    ],
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration_minutes: 75,
    release_date: '2024-12-15',
    season: 2,
    mood: 'insightful',
    guest_id: '1',
    created_at: '2024-12-15',
    guest: mockGuests[0],
    topics: [{ topic: mockTopics[0] }, { topic: mockTopics[3] }],
  },
  {
    id: '2',
    title: 'رحلة ريادة الأعمال: من الفكرة إلى النجاح',
    slug: 'entrepreneurship-journey',
    summary: 'أحمد العلي يشاركنا قصته في تأسيس شركته الأولى والتحديات التي واجهها. نتعلم من أخطائه ونجاحاته في عالم ريادة الأعمال.',
    key_takeaways: [
      'الفشل جزء طبيعي من رحلة النجاح',
      'بناء فريق قوي أهم من الفكرة نفسها',
      'التعلم المستمر هو مفتاح البقاء في السوق',
    ],
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration_minutes: 90,
    release_date: '2024-12-01',
    season: 2,
    mood: 'inspiring',
    guest_id: '2',
    created_at: '2024-12-01',
    guest: mockGuests[1],
    topics: [{ topic: mockTopics[4] }, { topic: mockTopics[1] }],
  },
  {
    id: '3',
    title: 'اكتشاف الذات: رحلة نحو الوعي',
    slug: 'self-discovery',
    summary: 'نورة القحطاني تأخذنا في رحلة عميقة لاستكشاف الذات وفهم أنفسنا بشكل أفضل. كيف نتعرف على قيمنا الحقيقية ونعيش بشكل أصيل.',
    key_takeaways: [
      'معرفة الذات تبدأ بالصمت والتأمل',
      'قيمنا الحقيقية تظهر في أفعالنا لا أقوالنا',
      'التغيير الحقيقي يبدأ من الداخل',
    ],
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration_minutes: 65,
    release_date: '2024-11-15',
    season: 2,
    mood: 'reflective',
    guest_id: '3',
    created_at: '2024-11-15',
    guest: mockGuests[2],
    topics: [{ topic: mockTopics[1] }, { topic: mockTopics[2] }],
  },
  {
    id: '4',
    title: 'قيادة الفرق التقنية في العصر الرقمي',
    slug: 'tech-leadership',
    summary: 'م. خالد الشمري يتحدث عن تحديات قيادة الفرق التقنية وكيفية بناء ثقافة عمل إيجابية ومنتجة.',
    key_takeaways: [
      'القائد الجيد يستمع أكثر مما يتكلم',
      'الثقة أساس كل فريق ناجح',
      'التوازن بين العمل والحياة ضرورة وليس رفاهية',
    ],
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration_minutes: 80,
    release_date: '2024-11-01',
    season: 2,
    mood: 'practical',
    guest_id: '4',
    created_at: '2024-11-01',
    guest: mockGuests[3],
    topics: [{ topic: mockTopics[4] }],
  },
  {
    id: '5',
    title: 'التعامل مع القلق في العصر الحديث',
    slug: 'dealing-with-anxiety',
    summary: 'د. سارة الأحمد تعود لتتحدث عن القلق وكيف أصبح جزءاً من حياتنا اليومية. نتعلم استراتيجيات عملية للتعامل معه.',
    key_takeaways: [
      'القلق شعور طبيعي لكن يمكن إدارته',
      'التنفس العميق أداة قوية ومجانية',
      'طلب المساعدة قوة وليس ضعفاً',
    ],
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration_minutes: 70,
    release_date: '2024-10-15',
    season: 1,
    mood: 'supportive',
    guest_id: '1',
    created_at: '2024-10-15',
    guest: mockGuests[0],
    topics: [{ topic: mockTopics[3] }, { topic: mockTopics[1] }],
  },
]

export const mockTimestamps: Timestamp[] = [
  { id: '1', episode_id: '1', time_seconds: 0, title: 'المقدمة', description: 'تعريف بالضيفة وموضوع الحلقة' },
  { id: '2', episode_id: '1', time_seconds: 300, title: 'ما هي العلاقة الصحية؟', description: 'تعريف وأسس العلاقات الصحية' },
  { id: '3', episode_id: '1', time_seconds: 900, title: 'التواصل الفعال', description: 'كيف نتواصل بشكل أفضل' },
  { id: '4', episode_id: '1', time_seconds: 1800, title: 'وضع الحدود', description: 'أهمية الحدود الصحية' },
  { id: '5', episode_id: '1', time_seconds: 2700, title: 'أسئلة المستمعين', description: 'إجابات على أسئلة الجمهور' },
  { id: '6', episode_id: '1', time_seconds: 4000, title: 'الخاتمة', description: 'ملخص ونصائح أخيرة' },
]

export const mockQuotes: (Quote & { guest?: Guest })[] = [
  {
    id: '1',
    episode_id: '1',
    guest_id: '1',
    text: 'العلاقة الصحية ليست خالية من المشاكل، بل هي التي نتعلم فيها كيف نحل مشاكلنا معاً.',
    theme: 'العلاقات',
    created_at: '2024-12-15',
    guest: mockGuests[0],
  },
  {
    id: '2',
    episode_id: '2',
    guest_id: '2',
    text: 'الفشل ليس عكس النجاح، بل هو جزء من الطريق إليه.',
    theme: 'ريادة الأعمال',
    created_at: '2024-12-01',
    guest: mockGuests[1],
  },
  {
    id: '3',
    episode_id: '3',
    guest_id: '3',
    text: 'لن تستطيع أن تحب الآخرين حقاً حتى تتعلم كيف تحب نفسك أولاً.',
    theme: 'تطوير الذات',
    created_at: '2024-11-15',
    guest: mockGuests[2],
  },
  {
    id: '4',
    episode_id: '1',
    guest_id: '1',
    text: 'الاستماع الحقيقي يعني أن تضع هاتفك جانباً وتنظر في عيني من يتحدث إليك.',
    theme: 'التواصل',
    created_at: '2024-12-15',
    guest: mockGuests[0],
  },
]

export const mockResources: Resource[] = [
  { id: '1', episode_id: '1', title: 'كتاب: لغات الحب الخمس', url: 'https://example.com/book1', type: 'book' },
  { id: '2', episode_id: '1', title: 'مقال: أسس التواصل الفعال', url: 'https://example.com/article1', type: 'article' },
  { id: '3', episode_id: '2', title: 'كتاب: من الصفر إلى الواحد', url: 'https://example.com/book2', type: 'book' },
  { id: '4', episode_id: '3', title: 'كتاب: قوة الآن', url: 'https://example.com/book3', type: 'book' },
]
